### ISSUE TITLE
How to use with a spinning image on pending?

### ISSUE THREAD

**Issue by drewbaker** [dockyard/ember-async-button#38]
This might be an obvious one, but how can I use this button with a spinning image when it's in the pending state? 

Or am I better just going manual style like this: http://guides.emberjs.com/v1.10.0/cookbook/helpers_and_components/spin_button_for_asynchronous_actions/

Thanks!

**Comment by amk221** [comment]
Something like this would be nice. But I don't think the component is yielded?

    {{#async-button action='something' as |button|}}
      {{#if button.pending}}
        <img src="spinner.gif">
       {{else}}
         do something
       {{/if}}
    {{/async-button}}

**Comment by danmcclain** [comment]
You can pass a computed to the `pending` property of `<img src="spinner.gif">` and it will be rendered un-escaped. I can provide a JSbin a bit later

**Comment by danmcclain** [comment]
@drewbaker http://output.jsbin.com/qokogasilu/1/edit?html,js,output The component in the JSBin is roughly equivalent, but note the `asyncPendingText` property on the `IndexController`

**Comment by amk221** [comment]
What might we do in this situation:

    {{#each models as |model|}}
      {{#x-foo model=model}}
        {{#async-button model action='toggle'}} 
         {{!noComputedPropertyAvailable}}
         {{#if buttonIsPending?}} Please wait... {{else}} Toggle {{/if}}
        {{/#async-button}}
      {{/x-foo}}
    {{/each}}

**Comment by danmcclain** [comment]
You have more than just pending, if this was the case, you want to have a `button.isFulfilled` `button.isRejected`, really you want a set up a set of sub-templates, one for default/fulfilled/rejected/pending, where default is the one the shows up if none of the other are entered

**Comment by amk221** [comment]
Would you be able to show an example?

My thoughts are it would be nice if [the button template](../blob/ac42007a4572e6e326d9981905e36751ae76d5e3/addon/templates/components/async-button.hbs) yielded `this` to provide access to the its state. Then we could do [this](#issuecomment-97847401).

**Comment by aMahdavian** [comment]
You could also achieve this using css transitions, as you know in the pending state, a 'pending' class is added to the button, the below example makes use of this class: 
http://jsbin.com/redefaquma/1/edit?html,css,js,output

> This is based on following snippet:
http://bootsnipp.com/snippets/featured/loading-button-effect-no-js

**Comment by kevinjalbert** [comment]
This works perfectly for me. It might be worth adding a section of this on the readme?

**Comment by drspaniel** [comment]
Kinda fixed with #52, further extended in #71. Closing for now, feel free to have any further discussion in #57
