### ISSUE TITLE
Controller properties unavailable in subexpressions in ember-cli-async-button's parameters

### ISSUE THREAD

**Issue by lolmaus** [dockyard/ember-async-button#41]
In my page controller I have created the following property:

    foo: true

Now, in my page template I'm doing this:

```hbs
{{ ember-cli-async-button default=(if foo 'Hello' 'World') }}
```

A button with no text as rendered!

At the same time, these work fine:

```hbs
{{ ember-cli-async-button default=(if true 'Hello' 'World') }} -- rendes button with `Hello`
{{ ember-cli-async-button default=foo }} -- rendes button with `true`
```

![dafuq](http://cdn2.business2community.com/wp-content/uploads/2014/06/thumb.jpg)

I've tried reproducing the problem with a boilerplate component.

I have created an `app/templates/components/x-bar.hbs` file with the following content:

```hbs
{{ default }}
```

Now, in my page template I'm doing this:

```hbs
{{ x-bar default=(if foo 'Hello' 'World') }}
```

It renders as `Hello`. Thus I conclude that the issue is specific to `ember-cli-async-button`.

**Comment by lolmaus** [comment]
The problem also exists for attribute bindings, e. g. `disabled`.

**Comment by bcardarella** [comment]
@lolmaus I suspect this issue is because we are proxying to the component through a helper and your options are being washed out. With https://github.com/emberjs/ember.js/pull/11028 we should be able to support what one want once this gets into Release Ember

**Comment by lolmaus** [comment]
You're right. I did this and it worked!

```coffee
`import AsyncButton from 'ember-cli-async-button/components/async-button'`

AssButtComponent = AsyncButton.extend()

`export default AssButtComponent`
```
