### ISSUE TITLE
Attribute binding syntax throwing deprecation warnings.

### ISSUE THREAD

**Issue by arenoir** [dockyard/ember-async-button#42]
Using this addon with Ember 11.1 I am receiving the following deprecation warnings.

```
DEPRECATION: You're attempting to render a view by passing pendingBinding to a view helper, but this syntax is deprecated. You should use `pending=someValue` instead.
```

@danmcclain is it still the [case](https://github.com/dockyard/ember-cli-async-button/blob/master/addon/helpers/async-button.js#L23) that the attribute binding syntax need to be changed for the component to automatically register it?

**Comment by drspaniel** [comment]
Looks like this has been fixed
