### ISSUE TITLE
Button type is not submit in phantomJS for some odd reason

### ISSUE THREAD

**Issue by toranb** [dockyard/ember-async-button#50]
I've found that phantomJS doesn't seem to respect the line below (making the type of the button truly submit). Is this a known issue/ does a workaround or explanation exist anywhere that I could read up on this? Mostly curious why chrome generates the correct html and phantom 1.9.16 doesn't

https://github.com/dockyard/ember-cli-async-button/blob/master/addon/components/async-button.js#L17

Thanks again for maintaining such a great OSS project !

**Comment by toranb** [comment]
Looks like I found the answer to both this and the comment I put in PR #46 

https://github.com/tildeio/htmlbars/pull/353#issuecomment-106348834

**Comment by jayphelps** [comment]
Actually, that PR (while touching the same code path) is for a different issue, albeit similar. `<button`> `type` issue was reported here https://github.com/emberjs/ember.js/issues/11112 and fixed here https://github.com/tildeio/htmlbars/pull/355
