### ISSUE TITLE
Button text is not reverting to default when rejected

### ISSUE THREAD

**Issue by devinus** [dockyard/ember-async-button#63]
I have a `fulfilled` text defined but not a `rejected`, and when rejected the button stays with the `fulfilled` text rather than defaulting to `default` as the docs mention.

> `rejected`
> Special text used if the promise is rejected. If not provided will use the default value.

**Comment by bcardarella** [comment]
@devinus are you using the block form? The block form won't change: https://github.com/dockyard/ember-cli-async-button/blob/master/addon/templates/components/async-button.hbs

However if you aren't https://github.com/dockyard/ember-cli-async-button/blob/master/addon/components/async-button.js#L46-L48 *should* be falling back `default` assuming that `textState` is falsey.

**Comment by drspaniel** [comment]
@devinus Did you ever resolve this? I'm closing for now since we didn't hear from you, but feel free to re-open.
