### ISSUE TITLE
Upgrade ember-cli-htmlbars

### ISSUE THREAD

**Issue by devinus** [DockYard/ember-async-button#87]
This will get rid of these warnings:

```DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/devinus/Projects/rebelmail-dashboard/node_modules/ember-cli/lib/models/addon.js:1009:27)```

**Comment by rwjblue** [comment]
Mind submitting a PR?

**Comment by Dhaulagiri** [comment]
@devinus what version of ember-asyc-button are you using?  The most recent version should be getting an updated version of ember-cli-htmlbars because the version is allowed to float [here](https://github.com/DockYard/ember-async-button/blob/master/package.json#L43)

**Comment by martndemus** [comment]
Fixed with #88!
