### ISSUE TITLE
Keep size of the button

### ISSUE THREAD

**Issue by cbou** [DockYard/ember-async-button#93]
I quickly try this addon in our app. It works quite well but I faced a problem.

The width of the button is changed because the size of the text changes. It would be great to have something out of the box in Ember-Async-Button.

**Comment by bcardarella** [comment]
@cbou This should be something that you can control with CSS. We don't want to make any assumptions on how you style your button.

**Comment by cbou** [comment]
I know and that was my first option too but it does not work with the behaviour that buttons should get their size according to the text content.

**Comment by bcardarella** [comment]
@cbou I'm not exactly sure what you're asking. Do you want the button size to be dynamic and grow with the text or do you want the size of the button to stay static regardless of the text?

**Comment by cbou** [comment]
Well it's both.

Look at the button in Github "Edit" and "New issue". 

The size of each button depends on the text of each (Edit is smaller than New issue).

If we would use Ember-Async-Button the text of would change from "New issue" to "Save" (which is longer than "New issue").

I won't expect the button be smaller because otherwise it will change the position of Edit (even wort if there are more than one button after the clicked one).

I expect the size to be dynamic and change with the default text (when not clicked). But I expect the size of the button in pending state (after click) to match the size in default text mode (at least not smaller).

I hope my explanation makes sense...

**Comment by bcardarella** [comment]
@cbou I see. So I think css is still your best best. Each state of the button applies itself so you can style that: https://github.com/DockYard/ember-async-button#styling

In addition, if you have multiple async buttons on the same page you can add your own css class to distinguish between them:

```hbs
{{async-button action="save" default="Save" pending="Saving..." class="custom-button"}}
```
