### ISSUE TITLE
Feature Request default config for all buttons

### ISSUE THREAD

**Issue by jstoup111** [DockYard/ember-async-button#94]
I've got a case where I'd like to set the same value for `pending` across all buttons. It'd be nice to have a config to globally set this.

I'd also like to include HTML as the default `pending` option. I wasn't able to extend this component in my own code. Any chance of showing how I can extend it for this functionality, or adding this?

**Comment by bcardarella** [comment]
you can just reopen the component and set the property directly.

**Comment by jstoup111** [comment]
I'm having issues importing the component to reopen it. Do you have a quick code snippet I can try?

```
AsyncButton.reopen({
  pending: '<h1>Test</h1>'
});
```

The above says AsyncButton is not defined. How can I import it to reopen it?

**Comment by jstoup111** [comment]
Nevermind I figured it out. For anyone else looking.

`import AsyncButton from 'ember-async-button/components/async-button';`

**Comment by bcardarella** [comment]
Sure, in your app create a new file: `app/components/async-button.js` with the content:

```js
import AsyncButtonComponent from 'ember-async-button/components/async-button';

export default AsyncButtonComponent.extend({
  pending: 'default-value'
});
```
